// Regenerated by scripts/embed-assets.ts as part of `bun run compile`, then
// restored to this empty stub afterward so the working tree stays clean.
// Empty here means: no frontend baked in — used by `bun run dev` and the
// Docker image, which both serve the frontend a different way (Vite dev
// server / apps/api/public respectively). Only a `bun run compile`d
// standalone binary ever sees this non-empty.
export const embeddedAssets: Record<string, { contentType: string; base64: string }> = {};
