// Reads the built frontend (apps/web/dist) and writes it into
// embeddedAssets.generated.ts as base64 strings, so `bun build --compile`
// bakes the frontend straight into the standalone binary — no separate
// public/ folder needed at runtime. Run as part of `bun run compile`
// (repo root); scripts/compile.ts restores the stub afterward.
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const webDist = path.resolve(import.meta.dirname, "../../web/dist");
const outFile = path.resolve(import.meta.dirname, "../src/embeddedAssets.generated.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

async function collectFiles(dir: string, base = ""): Promise<Array<[string, string]>> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: Array<[string, string]> = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    const urlPath = `${base}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(full, urlPath)));
    } else {
      files.push([urlPath, full]);
    }
  }
  return files;
}

async function main(): Promise<void> {
  const files = await collectFiles(webDist);
  if (files.length === 0) {
    throw new Error(`No files found under ${webDist} — run the web build first.`);
  }

  const entries = await Promise.all(
    files.map(async ([urlPath, fsPath]) => {
      const buf = await readFile(fsPath);
      const contentType = CONTENT_TYPES[path.extname(fsPath)] ?? "application/octet-stream";
      return `  ${JSON.stringify(urlPath)}: { contentType: ${JSON.stringify(contentType)}, base64: ${JSON.stringify(buf.toString("base64"))} },`;
    })
  );

  const content = `// Auto-generated by apps/api/scripts/embed-assets.ts — do not edit by hand.
export const embeddedAssets: Record<string, { contentType: string; base64: string }> = {
${entries.join("\n")}
};
`;

  await Bun.write(outFile, content);
  console.log(`Embedded ${files.length} frontend assets into ${path.relative(process.cwd(), outFile)}`);
}

main().catch((err) => {
  console.error("Failed to embed frontend assets:", err);
  process.exit(1);
});
